require("neocomplete.lsp_source")
vim.keymap.set("i", "<tab>", function()
    vim.snippet.jump(1)
end)
vim.keymap.set("i", "<s-tab>", function()
    vim.snippet.jump(-1)
end)
vim.keymap.set("i", "<c-j>", function()
    require("neocomplete").core.menu:select_next(1)
end)
vim.keymap.set("i", "<c-e>", function()
    require("neocomplete").core.menu:close()
end)
vim.keymap.set("i", "<c-k>", function()
    require("neocomplete").core.menu:select_prev(1)
end)
vim.keymap.set("i", "<cr>", function()
    require("neocomplete").core.menu:confirm()
end)
vim.api.nvim_create_autocmd("InsertLeave", {
    callback = function()
        require("neocomplete").core.menu:close()
    end,
})
