--- Configuration for neocomplete.nvim
---@class neocomplete.config
--- Configuration for the ui of neocomplete
---@field ui neocomplete.config.ui
--- Function used to expand snippets
---@field snippet_expansion fun(string): nil
--- Behavior when selecting entry
---@field selection_behavior "select"|"insert"
--- Pattern used to determine keywords
---@field keyword_pattern string
--- Configuration for the ui of neocomplete
---@field enabled fun(): boolean
--- The main class for the ui configuration of neocomplete.nvim
---@class neocomplete.config.ui
--- Configuration of the completion menu of neocomplete.nvim
---@field menu neocomplete.config.ui.menu
--- Configuration of the documentation view of neocomplete.nvim
---@field docs_view neocomplete.config.ui.docs
--- The icons for the different compltion item kinds
---@field type_icons neocomplete.config.ui.type_icons
--- Whether to show ghost text
---@field ghost_text boolean
--- Configuration of the completion menu of neocomplete.nvim
---@class neocomplete.config.ui.menu
--- Maximum height of the menu
---@field max_height integer
--- The border of the completion menu
---@field border string|string[]|string[][]
--- Character used for the scrollbar
---@field scrollbar string?
--- Position of the menu
---@field position "auto"|"bottom"|"top"
--- How an entry should be formatted
---@field format_entry fun(entry: neocomplete.entry): { [1]: string, [2]: string }[][]
--- How the sections in the menu should be aligned
---@field alignment ("left"|"center"|"right")[]
--- Configuration of the completion menu of neocomplete.nvim
---@class neocomplete.config.ui.docs
--- Maximum height of the documentation view
---@field max_height integer
--- Maximum width of the documentation view
---@field max_width integer
--- The border of the documentation view
---@field border string|string[]|string[][]
--- Character used for the scrollbar
---@field scrollbar string
--- The icons used for the different completion item types
---@alias neocomplete.config.ui.type_icons table<string, string>