---@class neocomplete.docs_view
--- Winnr of the docs window
---@field winnr? integer
--- The current top line of the window
---@field current_scroll integer
--- Creates a new view
---@field new fun(entry: neocomplete.entry, x_offset: integer, position: "above"|"below", config: neocomplete.config.ui.docs): neocomplete.docs_view?
--- Buffer used for view
---@field bufnr integer
--- Scroll the window up or down
---@field scroll fun(self: neocomplete.docs_view, delta: integer)
--- Sets the scroll to a certain line
---@field set_scroll fun(self: neocomplete.docs_view, line: integer)
