---@class neocomplete.window
--- Creates a new instance of the menu window
---@field new fun(): neocomplete.window
---@field winnr? integer
--- Instance of the neocomplete config
---@field config neocomplete.config
---@field buf integer
--- Whether the window is currently opened above or below the cursor
---@field position? "above"|"below"
--- Data for the scrollbar of the window
---@field scrollbar {win: integer, buf: integer}
--- The maximum available height where the window is currently open
---@field max_height integer
--- Method to check whether the window is open or not
---@field is_open fun(self: neocomplete.window): boolean
--- Method to check whether the scrollbar window is open or not
---@field scrollbar_is_open fun(self: neocomplete.window): boolean
--- Adjust the window size to new entries. Modifies height and width while keeping position
---@field readjust fun(self: neocomplete.window, content_len: integer, width: integer, offset: integer): nil
--- Opens the window for the scrollbar
---@field open_scrollbar_win fun(self: neocomplete.window, width: integer, height: integer, offset: integer): nil
--- Closes the window and the scrollbar window and resets fields
---@field close fun(self: neocomplete.window): nil
--- Sets the scroll of the window
---@field set_scroll fun(self: neocomplete.window, index: integer, direction: integer): nil
--- Opens a new main window
---@field open_cursor_relative fun(self: neocomplete.window, width: integer, wanted_height: integer, offset: integer, config: neocomplete.config.ui.docs|neocomplete.config.ui.menu): nil
--- Draw the scrollbar for the window if needed
---@field draw_scrollbar fun(self: neocomplete.window): nil
--- Change scroll of window
---@field scroll fun(self: neocomplete.window, delta: integer)
--- Where the window was last opened
---@field opened_at {row: integer, col: integer}
--- Namespace used for setting extmarks
---@field ns integer
--- Current scroll of the window
---@field current_scroll integer
