--- Context provided to completion sources
---@class care.context
--- Context changed since previous
---@field changed fun(care.context): boolean
--- Create a new context
---@field new fun(previous: care.context?): care.context
--- The previous context
---@field previous care.context?
--- The cursor position
---@field cursor care.context.cursor
--- The number of the buffer
---@field bufnr integer
--- Reason for triggering completion
---@field reason care.completionReason?
--- Current line
---@field line string
--- Line before cursor
---@field line_before_cursor string
--- A cursor position
---@class care.context.cursor
---@field row integer
---@field col integer
