--- Internal class for care to store source metadata
---@class care.internal_source
--- The external completion source
---@field source care.source
--- The entries recieved by last completion
---@field entries care.entry[]
--- The entries recieved by last completion
---@field new fun(completion_source: care.source): care.internal_source
--- Whether the source is incomplete
---@field incomplete boolean
--- Get the keyword pattern
---@field get_keyword_pattern fun(self: care.internal_source): string
--- The offset at which completions from source were loaded
---@field get_offset fun(self: care.internal_source, context: care.context): integer
---Get the trigger characters
---@field get_trigger_characters fun(self: care.internal_source): string[]
--- The configuration for the source
---@field config neocomplete.config.source
--- Whether the source is enabled or not
---@field is_enabled fun(self: care.internal_source): boolean
